server:
  port: 9083

spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000   # 连接超时时间
        readTimeout: 5000      # 读取超时时间

#logging:
#  level:
#    org.example.learn.spring.cloud.feign.order.third.UserServiceClient: FULL # 启用详细日志